resolver: lts-20.2
packages:
- monad-callstack
- monad-fs-reader
- monad-fs-writer
- monad-ioref
- monad-logger-namespace
- monad-stm
- monad-terminal
- monad-thread
- monad-time
ghc-options:
  "$locals":
    -Wall -Wcompat -Werror -Widentities
    -Wincomplete-record-updates -Wincomplete-uni-patterns
    -Wmissing-home-modules -Wmissing-export-lists -Wpartial-fields
    -Wredundant-constraints -Wunused-packages -Wmissing-deriving-strategies
    -Wprepositive-qualified-module
nix:
  shell-file: nix/stack.nix
