name: "cabal"

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  cabal:
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - ghc: "8.10.7"
            proj: "--project-file cabal.project.legacy"
          - ghc: "9.0.2"
            proj: "--project-file cabal.project.legacy"
          - ghc: "9.2.7"
            proj: "--project-file cabal.project.legacy"
          - ghc: "9.4.4"
            proj: "--project-file cabal.project.legacy"
          - ghc: "9.6.1"
            proj: ""
        os:
          - "macos-latest"
          - "ubuntu-latest"
          - "windows-latest"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3.5.0

      - uses: haskell/actions/setup@v2.3.7
        with:
          ghc-version: ${{ matrix.compiler.ghc }}

      - name: Configure
        run: cabal configure --enable-tests

      - name: Compile
        run: cabal build all ${{ matrix.compiler.proj }}

      - name: Test effects-exceptions
        run: cabal test effects-exceptions

      - name: Test effects-fs
        run: cabal test effects-fs ${{ matrix.compiler.proj }}

      - name: Test effects-logger-ns
        run: cabal test effects-logger-ns

      - name: Test effects-time
        run: cabal test effects-time --test-options '--hedgehog-tests 100000'