name: "cabal"

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  cabal:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ghc:
          - "8.10.7"
          - "9.0.2"
          - "9.2.5"
          - "9.4.4"
    steps:
      - uses: actions/checkout@v3.0.2

      - uses: haskell/actions/setup@v2.0.0
        with:
          ghc-version: ${{ matrix.ghc }}

      - name: Configure
        run: cabal configure --enable-tests

      - name: Compile
        run: cabal build all

      - name: Test monad-callstack
        run: cabal test monad-callstack

      - name: Test monad-logger-namespace
        run: cabal test monad-logger-namespace

      - name: Test monad-system-time
        run: cabal test monad-system-time --test-options '--hedgehog-tests 100000'