name: "stack"

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  stack:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        stack_yaml:
          - stack_lts-18.yaml
          - stack_lts-19.yaml
          - stack.yaml
          - stack_nightly.yaml
    steps:
      - uses: actions/checkout@v3.0.2

      - uses: haskell/actions/setup@v2.0.0
        with:
          enable-stack: true

      - name: Compile
        env:
          STACK_YAML: ${{ matrix.stack_yaml }}
        run: stack build

      - name: Test monad-callstack
        env:
          STACK_YAML: ${{ matrix.stack_yaml }}
        run: stack test monad-callstack

      - name: Test monad-logger-namespace
        env:
          STACK_YAML: ${{ matrix.stack_yaml }}
        run: stack test monad-logger-namespace

      - name: Test monad-system-time
        env:
          STACK_YAML: ${{ matrix.stack_yaml }}
        run: stack test monad-system-time --test-arguments '--hedgehog-tests 100000'